import json

# Load the JSON data
tasks = json.loads('''
[
  {
    "TaskID": 1,
    "TaskName": "Database Design",
    "Description": "Create ERD and define database schema.",
    "ProjectID": 1,
    "AssignedUserID": 1,
    "Status": "in_progress",
    "ExpectedHours": "10.50",
    "Priority": "high",
    "Deadline": "2025-03-10 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-02-28 08:33:54",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 2,
    "TaskName": "Backend API Development",
    "Description": "Develop RESTful APIs using Django.",
    "ProjectID": 2,
    "AssignedUserID": 5,
    "Status": "completed",
    "ExpectedHours": "20.00",
    "Priority": "medium",
    "Deadline": "2025-03-15 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-03-07 19:44:10",
    "IsTaskVerified": 1,
    "VerifiedByUserID": 5,
    "AssignedByUserID": null,
    "CompletedDateUTC": "2025-03-02 17:32:54",
    "CompletedByUserID": 5,
    "VerifiedDateUTC": "2025-03-03 17:43:08"
  },
  {
    "TaskID": 3,
    "TaskName": "React UI Implementation",
    "Description": "Integrate CoreUI templates into React frontend.",
    "ProjectID": 3,
    "AssignedUserID": 1,
    "Status": "queue",
    "ExpectedHours": "18.00",
    "Priority": "high",
    "Deadline": "2025-03-20 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-02-28 08:33:54",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 4,
    "TaskName": "User Authentication",
    "Description": "Implement JWT authentication in Django.",
    "ProjectID": 4,
    "AssignedUserID": 5,
    "Status": "queue",
    "ExpectedHours": "12.00",
    "Priority": "urgent",
    "Deadline": "2025-03-05 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-03-01 19:02:09",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 5,
    "TaskName": "Setup CI/CD Pipeline",
    "Description": "Configure GitHub Actions for automated deployment.",
    "ProjectID": 5,
    "AssignedUserID": 1,
    "Status": "queue",
    "ExpectedHours": "15.00",
    "Priority": "medium",
    "Deadline": "2025-03-12 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-02-28 08:33:54",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 6,
    "TaskName": "Testing & Debugging",
    "Description": "Perform unit and integration testing.",
    "ProjectID": 1,
    "AssignedUserID": 6,
    "Status": "in_progress",
    "ExpectedHours": "25.00",
    "Priority": "high",
    "Deadline": "2025-03-25 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-03-26 00:33:35",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 7,
    "TaskName": "Optimize SQL Queries",
    "Description": "Improve MySQL query performance.",
    "ProjectID": 7,
    "AssignedUserID": 1,
    "Status": "queue",
    "ExpectedHours": "14.00",
    "Priority": "medium",
    "Deadline": "2025-03-22 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-02-28 08:33:54",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 8,
    "TaskName": "Write Project Documentation",
    "Description": "Prepare technical and user documentation.",
    "ProjectID": 8,
    "AssignedUserID": 5,
    "Status": "queue",
    "ExpectedHours": "8.00",
    "Priority": "low",
    "Deadline": "2025-04-01 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-03-01 19:02:09",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 9,
    "TaskName": "UI Enhancements",
    "Description": "Improve UI/UX design based on user feedback.",
    "ProjectID": 9,
    "AssignedUserID": 1,
    "Status": "queue",
    "ExpectedHours": "12.00",
    "Priority": "medium",
    "Deadline": "2025-03-28 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-02-28 08:33:54",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 10,
    "TaskName": "Deploy to Production",
    "Description": "Deploy the final application version.",
    "ProjectID": 2,
    "AssignedUserID": 5,
    "Status": "queue",
    "ExpectedHours": "5.00",
    "Priority": "urgent",
    "Deadline": "2025-04-05 23:59:59",
    "CreatedDateUTC": "2025-02-28 08:33:54",
    "ModifiedDateUTC": "2025-03-07 19:45:50",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 11,
    "TaskName": "Market Research",
    "Description": "Conduct thorough market research to identify target audience demographics, preferences, and competitor strategies. Analyze data to create insights for the campaign.",
    "ProjectID": 13,
    "AssignedUserID": 1,
    "Status": "in_progress",
    "ExpectedHours": "15.00",
    "Priority": "medium",
    "Deadline": "2025-03-07 23:11:00",
    "CreatedDateUTC": "2025-03-01 17:41:44",
    "ModifiedDateUTC": "2025-03-01 17:41:44",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 12,
    "TaskName": "Dummy Task - Auto Generated",
    "Description": "Created automatically as no tasks were selected.",
    "ProjectID": 16,
    "AssignedUserID": 9,
    "Status": "in_progress",
    "ExpectedHours": "0.00",
    "Priority": "low",
    "Deadline": null,
    "CreatedDateUTC": "2025-03-05 18:25:31",
    "ModifiedDateUTC": "2025-03-05 18:25:31",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 13,
    "TaskName": "Dummy Task - Auto Generated",
    "Description": "Created automatically as no tasks were selected.",
    "ProjectID": 16,
    "AssignedUserID": 10,
    "Status": "in_progress",
    "ExpectedHours": "0.00",
    "Priority": "low",
    "Deadline": null,
    "CreatedDateUTC": "2025-03-07 14:42:50",
    "ModifiedDateUTC": "2025-04-01 22:57:41",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": 10,
    "CompletedDateUTC": "2025-04-01 17:27:41",
    "CompletedByUserID": 10,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 20,
    "TaskName": "Dummy Task - Auto Generated",
    "Description": "Created automatically as no tasks were selected.",
    "ProjectID": 16,
    "AssignedUserID": 6,
    "Status": "in_progress",
    "ExpectedHours": "0.00",
    "Priority": "low",
    "Deadline": null,
    "CreatedDateUTC": "2025-03-07 16:58:52",
    "ModifiedDateUTC": "2025-03-07 16:58:52",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 21,
    "TaskName": "This is a dummy task",
    "Description": "This is a dummy task to verify the flow",
    "ProjectID": 17,
    "AssignedUserID": 10,
    "Status": "in_progress",
    "ExpectedHours": "15.00",
    "Priority": "high",
    "Deadline": "2025-03-17 16:14:00",
    "CreatedDateUTC": "2025-03-12 19:47:30",
    "ModifiedDateUTC": "2025-03-12 20:07:00",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 22,
    "TaskName": "Dummy Task - Auto Generated",
    "Description": "Created automatically as no tasks were selected.",
    "ProjectID": 16,
    "AssignedUserID": 10,
    "Status": "in_progress",
    "ExpectedHours": "0.00",
    "Priority": "low",
    "Deadline": null,
    "CreatedDateUTC": "2025-03-12 20:27:18",
    "ModifiedDateUTC": "2025-03-25 10:23:28",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": 10,
    "CompletedDateUTC": "2025-03-25 04:53:28",
    "CompletedByUserID": 10,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 23,
    "TaskName": "This is a dummy task to support the project",
    "Description": "This is a dummy task to support the project",
    "ProjectID": 18,
    "AssignedUserID": 1,
    "Status": "in_progress",
    "ExpectedHours": "15.00",
    "Priority": "high",
    "Deadline": "2025-03-18 10:30:00",
    "CreatedDateUTC": "2025-03-15 10:24:54",
    "ModifiedDateUTC": "2025-03-15 10:24:54",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  },
  {
    "TaskID": 24,
    "TaskName": "Design and implement the database schema to store employee data",
    "Description": "Create a database schema to store employee information, including tables for employee personal details, job roles, and performance metrics",
    "ProjectID": 19,
    "AssignedUserID": 7,
    "Status": "in_progress",
    "ExpectedHours": "5.00",
    "Priority": "high",
    "Deadline": "2025-03-25 19:09:00",
    "CreatedDateUTC": "2025-03-23 13:39:08",
    "ModifiedDateUTC": "2025-03-23 13:39:08",
    "IsTaskVerified": 0,
    "VerifiedByUserID": null,
    "AssignedByUserID": null,
    "CompletedDateUTC": null,
    "CompletedByUserID": null,
    "VerifiedDateUTC": null
  }
]
''')

# Define the table name and columns
table_name = 'tasks'
columns = ['TaskID', 'TaskName', 'Description', 'ProjectID', 'AssignedUserID', 'Status', 'ExpectedHours', 'Priority', 'Deadline', 'CreatedDateUTC', 'ModifiedDateUTC', 'IsTaskVerified', 'VerifiedByUserID', 'AssignedByUserID', 'CompletedDateUTC', 'CompletedByUserID', 'VerifiedDateUTC']

# Generate the SQL insert statements
sql_statements = []
for task in tasks:
    values = []
    for column in columns:
        value = task[column]
        if isinstance(value, str):
            value = f"'{value}'"
        values.append(value)
    sql_statement = f"INSERT INTO {table_name} ({', '.join(columns)}) VALUES ({', '.join(values)});"
    sql_statements.append(sql_statement)

# Print the SQL statements
for sql_statement in sql_statements:
    print(sql_statement)