# Generated by Django 4.2.7 on 2025-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_description_alter_user_photo_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('created_date', models.DateField()),
                ('industry_segment', models.CharField(max_length=100)),
                ('manufacturers_of', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('repeated_client', models.CharField(max_length=3)),
                ('contact_person', models.CharField(max_length=100)),
                ('gst_no', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
