# Generated by Django 4.2.7 on 2025-02-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
